server:
  port: 3000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_management_system_api
    username: postgres
    password: 311005Ge
  flyway:
    url: jdbc:postgresql://localhost:5432/employee_management_system_api
    user: postgres
    password: 311005Ge
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
    