spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource: 
    url: jdbc:mysql://localhost:3306/employee_management_system_api
    username: root
    password: 311005
    driver-class-name: com.mysql.cj.jdbc.Driver
    